### ISSUE TITLE
503 Service unavailable error

### ISSUE THREAD

**Issue by NinadNaik2811** [FolioReader/FolioReader-Android#175]
This is my all projects
allprojects {
    repositories {
        jcenter()
        maven {url "http://dl.bintray.com/mobisystech/maven"}
        maven {
            url "https://maven.google.com/" }
    }
}

And this is in the app build.gradle: 

compile 'com.folioreader:folioreader:0.3.3'

I get this error:

Error:Could not GET 'http://dl.bintray.com/mobisystech/maven/org/readium/r2-parser/0.1.2/r2-parser-0.1.2.jar'. Received status code 503 from server: Service Unavailable

Can anyone tell me what I need to do to solve this error

**Comment by hrishikesh-kadam** [comment]
@NinadNaik2811 Status code 5xx are Server errors, you can read more here - [5xx Server errors](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_errors)

This is due to bintray's server error. Currently the jar is being downloaded from the link specified.

@mahavir155 We can close this issue.
